Note that in Python, line indentation matters because it indicates the structure of the program.

# `if` conditional

Formats:

```
if (boolean expression):
  # what to do when expression is true
```

If with else clause:
```
if (boolean expression):
  # what to do when expression is true
else:
  # what to do when expression is false
```

If with elif (else if):
```
if (boolean expression1):
  # what to do when expression1 is true
elif (boolean expression2):
  # what to do when expression2 is true
else:
  # what to do when all of the above is false
```

If both expression1 and expression2 is true, only the first action will be executed, not both.

If with multiple elif and else clause:
```
if (boolean expression1):
  # what to do when expression1 is true
elif (boolean expression2):
  # what to do when expression2 is true
elif (boolean expression3):
  # what to do when expression3 is true
elif (boolean expression4):
  # what to do when expression4 is true
else:
  # what to do when all of the above is false
```

In [1]:
if 1+2 > 1:
  print('a')
elif 2+3 > 1:
  print('b')
else:
  print('c')

a

In [ ]:
# Example if elif else
age = int(input('What is your age? '))
if age <= 1:
  print('baby')
elif age <= 5:
  print('toddler')
elif age <= 12:
  print('kid')
elif age <= 19:
  print('teenager')
else:
  print('adult')

What is your age? 9
kid

In [3]:
# Use == to compare values

age = 17
if age == 17:
  print('Sweet seventeen!')

# Use != to mean "not equal to"
if age != 17:
  print('Not seventeen')

# Other comparison operators: >  >=  <  <=

Sweet seventeen!

# `for` loop

```
for (variable) in (range):
  # what to do in each iteration
```

In [ ]:
# Example
for i in range(5):
  print(i, 'squared is equal to', i**2)

# Note: ** is exponentiation operation

0 squared is equal to 0
1 squared is equal to 1
2 squared is equal to 4
3 squared is equal to 9
4 squared is equal to 16

`range(5)` gives us a sequence of numbers starting from 0 up all the way to before 5 (which is 4).

`range` function can actually accept up to 3 input parameters.

```
range(start, end, step)
```
 - `start` defaults to 0
 - `step` defaults to 1

If only 1 parameter is specified, i.e. `range(5)` then this is the same as `range(0, 5, 1)` or `range(0, 5)`.

If only 2 parameters are specified, i.e. `range(2, 5)` then this is the same as `range(2, 5, 1)`.

In [ ]:
# Example
for i in range(2, 5):
  print('i =', i)

i = 2
i = 3
i = 4

In [5]:
# Example with step > 1
for i in range(20, 50, 7):
  print('i =', i)
print('----------')

i = 20
i = 27
i = 34
i = 41
i = 48
----------

In [6]:
# Can we go from high to low?
for i in range(5, 2):
  print('i =', i)

# Note: nothing will get printed

In [7]:
# Yes, we can go from high to low using negative step value
for i in range(5, 2, -1):
  print('i =', i)

i = 5
i = 4
i = 3

Important:

`range` function can only accept `int` parameters.
That means `start`, `stop`, `step` must all be of type `int`.

In [ ]:
# Invalid example
for i in range(2, 5, 0.5):
  print('i =', i)
# When run, Python will complain:
# TypeError: 'float' object cannot be interpreted as an integer

TypeError: ignored

# `while` loop

```
while (boolean condition):
  # what to repeat in each iteration
```

In [ ]:
# Example
start = 2
end = 5
step = 0.5
i = start
while i < end:
  print('i = ', i)
  i += step  # this is same as: i = i + step

i =  2
i =  2.5
i =  3.0
i =  3.5
i =  4.0
i =  4.5