This notebook contains some advanced Python3 syntax. You are not required to know these, but if you already mastered the basic syntax and want more challenge and want to learn a more succinct way of writing your code, you will find this to be interesting.

In [ ]:
count = 1

if count > 0:
  print('yes')
else:
  print('no')

# The above can also be written more succinctly as:
print('yes' if count > 0 else 'no')

In [ ]:
# Multiple assignment
# All these has the same effect of setting a=1, b=2, c=3, d=4
a, b, c, d = 1, 2, 3, 4
a, b, c, d = (1, 2, 3, 4)
a, b, c, d = [1, 2, 3, 4]

# What if we repeat the variables?
# In this example, a=1, b=4 
# b will be assigned value of 2, 3, and then 4; so the final value of b is 4
a, b, b, b = 1, 2, 3, 4

# If we do not care about using a value, we can discard it as _
# For example, this will set a=1, b=2, c=4
a, b, _, c = 1, 2, 3, 4

# This will set a=1, b=4
a, _, _, b = 1, 2, 3, 4

# Actually there's nothing special about _
# Remember that _ is a valid variable name
# By convention people usually use _ as the variable that we don't care about its value
# but it is still a variable that we can access its value
# For example:
a, _, _, b = 1, 2, 3, 4
print(_) # will print: 3

In [ ]:
myinput = "12 34 56 78"

a, b, c, d = myinput.split()
a, b, c, d = int(a), int(b), int(c), int(d)

# The above can also be written as:
a, b, c, d = [int(i) for i in myinput.split()]

# Or simply as:
a, b, c, d = map(int, myinput.split())

In [ ]:
# To generate a list of the first 10 squares:
mylist = [i**2 for i in range(1, 11)]
print(mylist) # will print: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]